Resources:
  ToDoListTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: arduino-connections
      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S
      KeySchema:
        - AttributeName: connectionId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1